# Generated by Django 4.2 on 2025-05-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_users', 'Can manage users'), ('manage_products', 'Can manage products'), ('manage_categories', 'Can manage categories')]},
        ),
    ]
