name: CI/CD Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main

env:
  REGISTRY: registry.digitalocean.com/dapperautobutique

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to DigitalOcean Container Registry
      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend image
      - name: Build and push backend image
        run: |
          docker build -t $REGISTRY/backend:latest ./backend
          docker push $REGISTRY/backend:latest

      # Build and push frontend image
      - name: Build and push frontend image
        run: |
          docker build -t $REGISTRY/frontend:latest ./frontend
          docker push $REGISTRY/frontend:latest

      # Instala kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      # Configura el kubeconfig
      - name: Set up KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      # Aplica los manifiestos de Kubernetes
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          kubectl apply -f k8s-manifiestos/postgres-deployment.yaml
          kubectl apply -f k8s-manifiestos/backend-deployment.yaml
          kubectl apply -f k8s-manifiestos/frontend-deployment.yaml